### ISSUE TITLE
Add bookmarklet to the readme

### ISSUE THREAD

**Issue by earshinov** [earshinov/tocit#2]
It would be nice to have on the [home page](https://github.com/earshinov/tocit/) a link that can be easily drag-and-dropped to browser's bookmarks bar instead of forcing users to add the bookmark manually as it is now.

**Comment by earshinov** [comment]
It is not possible: GitHub does not (and probably will not) support javascript links in markup: https://github.com/github/markup/issues/79#issuecomment-6140785

**Comment by Artistan** [comment]
works in github pages like https://retrography.github.io/VUTt/,
  but not in gists (same VUTt Link) https://gist.github.com/Artistan/2f212b8ea3d1ec0fbe3e1be1fbb7a987

**Comment by earshinov** [comment]
@Artistan Thank you for the information. I have now setup Github Pages (http://earshinov.github.io/tocit/) and enhanced the readme along the way.

**Comment by Artistan** [comment]
Nice!
