### ISSUE TITLE
"Installation" relies on rawgit.com, which is end of life

### ISSUE THREAD

**Issue by netjeff** [earshinov/tocit#5]
The "Installation" section of the README.md relies on rawgit.com.  According to the [rawgit.com homepage](https://rawgit.com/):

> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.

They recommend some other alternatives.  Seems like the Installation section should be updated before rawgit.com is shutdown for real?

**Comment by earshinov** [comment]
I will look for some other options. Thanks for the heads-up!
